import "./styles.css";
const wa="https://wa.me/2349015599988?text="+encodeURIComponent("Hello SAMMIX PAINT INDUSTRIAL LIMITED, I would like to make an enquiry/order.");
const products=[["Satin Paint","20L","₦60,000"],["Emulsion Paint","20L","₦13,000"],["Matt Paint","20L","₦28,000"],["Screeding Paint","20L","₦5,500"],["Textcoat Paint","Drum","₦18,000"],["Stucco Paint","Available","Price on request"],["Marble Trowel Paint","Available","Price on request"],["Gloss Paint","Available","Price on request"],["Gravito Paint","Available","Price on request"],["Satin Paint","4L","₦12,000"],["Emulsion Paint","4L","₦4,000"],["Screeding Paint","4L","₦3,000"]];
const work=["work-image-1.jpg","work-image-2.jpg","new-work-picture-1.jpg","new-work-picture-2.jpg","new-work-picture-3.jpg","new-work-picture-4.jpg"];
document.querySelector<HTMLDivElement>("#app")!.innerHTML=`
<header class="header"><div class="top"><span>WhatsApp: <a href="https://wa.me/2349015599988">0901 559 9988</a></span><span>WhatsApp: <a href="https://wa.me/2348071334476">0807 133 4476</a></span><span>Call: <a href="tel:+2349134682855">0913 468 2855</a></span><span><a href="mailto:Sammixpaintindustriallimited@gmail.com">Sammixpaintindustriallimited@gmail.com</a></span></div>
<nav><a class="brand" href="#home"><img src="/resources/sammix-logo.jpg" alt="SAMMIX logo" onerror="this.src='/resources/sammix-logo-placeholder.svg'"><span><b>SAMMIX PAINT</b><small>INDUSTRIAL LIMITED</small></span></a><button id="menu">☰</button><div id="links"><a href="#home">Home</a><a href="#products">Products</a><a href="#story">Our Story</a><a href="#vision">Vision & Mission</a><a href="#work">Our Work</a><a href="#values">Values</a><a href="#contact">Contact</a><a class="order" href="${wa}" target="_blank">Order Now</a></div></nav></header>
<main>
<section id="home" class="hero"><div><p class="eyebrow">QUALITY • INNOVATION • EXCELLENCE</p><h1>Colour your world with <span>confidence.</span></h1><p>Quality, affordable and reliable paint solutions created to add beauty and lasting value to homes, offices and businesses.</p><div class="buttons"><a class="btn yellow" href="#products">View Products</a><a class="btn ghost" href="${wa}" target="_blank">Order on WhatsApp</a></div><div class="trust"><span>✓ Quality first</span><span>✓ Customer focused</span><span>✓ Built to last</span></div></div><div class="hero-logo"><img src="/resources/sammix-logo.jpg" alt="SAMMIX" onerror="this.src='/resources/sammix-logo-placeholder.svg'"><b>RC: 8748853</b></div></section>
<section class="strip"><div><b>Quality Paint</b><small>Reliable colour and finish</small></div><div><b>Affordable</b><small>Value for homes and businesses</small></div><div><b>Painting Services</b><small>We also paint houses</small></div></section>
<section id="products" class="section"><div class="heading"><p class="eyebrow purple">OUR PRODUCTS</p><h2>Paint solutions for every project.</h2><p>Quality products for homes, offices, businesses and decorative projects.</p></div><div class="products">${products.map(p=>`<article class="card"><div class="can"><strong>SAMMIX</strong><small>PAINT</small></div><h3>${p[0]}</h3><small>${p[1]}</small><strong class="price">${p[2]}</strong><a class="smallbtn" href="${wa}" target="_blank">Order</a></article>`).join("")}</div></section>
<section id="story" class="section story"><div class="photo"><img src="/resources/work-image-1.jpg" alt="SAMMIX painting work" onerror="this.src='/resources/work-placeholder-1.svg'"></div><div><p class="eyebrow purple">OUR STORY</p><h2>Built from a simple vision.</h2><p>SAMMIX PAINT INDUSTRIAL LIMITED was born from a simple vision—to provide quality, affordable, and reliable paint products while adding beauty and value to homes, offices, and businesses.</p><p>The idea started with a passion for creativity, painting, and the desire to build something that could make a meaningful impact in the community.</p><p>We saw the need for paints that people could trust, products that combine good quality with affordability, and a company that puts customers first.</p><p>With determination, faith, and a willingness to learn and grow, what began as a vision gradually became a business.</p><p>Today, SAMMIX PAINT INDUSTRIAL LIMITED is growing with a bigger dream—to become a trusted and recognized name in the paint industry, creating quality products, empowering people, creating opportunities, and contributing positively to our community.</p></div></section>
<section id="vision" class="section dark"><div class="heading light"><p class="eyebrow">OUR DIRECTION</p><h2>Vision & Mission</h2></div><div class="vision"><article><b>01</b><h3>Our Vision</h3><p>“To be a leading African brand in quality, innovative, and durable paint solutions.”</p></article><article><b>02</b><h3>Our Mission</h3><p>“To provide quality and affordable paint products through innovation, excellence, customer satisfaction, and responsible manufacturing.”</p></article></div></section>
<section id="work" class="section"><div class="heading"><p class="eyebrow purple">OUR WORK</p><h2>See what SAMMIX can do.</h2><p>Our painting projects and completed work.</p></div><div class="gallery">${work.map((f,i)=>`<figure><img src="/resources/${f}" alt="SAMMIX completed project ${i+1}" onerror="this.src='/resources/work-placeholder-${(i%6)+1}.svg'"><figcaption>Completed SAMMIX painting project</figcaption></figure>`).join("")}</div><div class="videos"><video controls poster="/resources/video-poster.svg"><source src="/resources/work-video-1.mp4" type="video/mp4"></video><video controls poster="/resources/video-poster.svg"><source src="/resources/new-work-video.mp4" type="video/mp4"></video></div></section>
<section id="values" class="section values"><div class="heading"><p class="eyebrow purple">CORE VALUES</p><h2>What guides SAMMIX.</h2></div><div class="valuegrid">${[["Quality","We never compromise on the quality of our products."],["Integrity","We conduct our business honestly and responsibly."],["Innovation","We continuously improve our products and production methods."],["Customer Satisfaction","Our customers are at the heart of what we do."],["Excellence","We strive for excellence in every product and service we provide."]].map((v,i)=>`<article><b>0${i+1}</b><h3>${v[0]}</h3><p>${v[1]}</p></article>`).join("")}</div></section>
<section class="cta"><div><p class="eyebrow">READY TO PAINT?</p><h2>Let's bring your next project to life.</h2></div><a class="btn yellow" href="${wa}" target="_blank">Order / Enquire</a></section>
<section id="contact" class="section contact"><div><p class="eyebrow purple">CONTACT US</p><h2>We are here to help.</h2><p>Visit us, call us or send a WhatsApp message for product enquiries, orders and painting services.</p></div><div class="contactcard"><p><b>Address</b><br>Tipper Garage, before Dantata Estate Gate, Kubwa, Abuja, Nigeria</p><p><b>Call</b><br><a href="tel:+2349134682855">0913 468 2855</a></p><p><b>WhatsApp</b><br><a href="https://wa.me/2349015599988">0901 559 9988</a> · <a href="https://wa.me/2348071334476">0807 133 4476</a></p><p><b>Email</b><br><a href="mailto:Sammixpaintindustriallimited@gmail.com">Sammixpaintindustriallimited@gmail.com</a></p><p><a href="https://www.instagram.com/sogah931" target="_blank">Instagram</a> · <a href="https://www.facebook.com/profile.php?id=61590142258736" target="_blank">Facebook</a></p></div></section></main>
<footer><b>SAMMIX PAINT INDUSTRIAL LIMITED</b><span>Quality • Innovation • Excellence</span><span>© ${new Date().getFullYear()}</span></footer><a class="wa" href="${wa}" target="_blank">WA</a>`;
document.querySelector<HTMLButtonElement>("#menu")?.addEventListener("click",()=>document.querySelector("#links")?.classList.toggle("open"));
document.querySelectorAll("#links a").forEach(a=>a.addEventListener("click",()=>document.querySelector("#links")?.classList.remove("open")));
